---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ openvpn_const['RedHat']['dependencies'] }}"

- name: add third_party repo
  block:
    - name: import epel repo gpg key
      ansible.builtin.rpm_key:
        key: "{{ openvpn_const[ansible_os_family]['epel_gpg'] }}"
        state: present

    - name: install epel repo
      ansible.builtin.package:
        name: "{{ openvpn_const[ansible_os_family]['epel_repo'] }}"
        state: present
  when: openvpn.repo == "third_party"

- name: install openvpn packages.
  ansible.builtin.package:
    name: "{{ openvpn_const['RedHat']['packages'] }}"
    state: present
    update_cache: true

- name: "Make sure dir for log-files is present"
  ansible.builtin.file:
    path: "/var/log/openvpn/"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: "Make sure dir for client config is present"
  ansible.builtin.file:
    path: "/etc/openvpn/ccd/"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true