---
- name: include role firewalld
  include_role:
    name: darexsu.firewalld
  when: firewalld.enabled

- name: enable forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
  when: openvpn.net_ipv4_ip_forward